<a href="https://colab.research.google.com/github/Sargunnn/Machine-Learning-Lab/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Q1 (a)Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
# or np.flip(arr)
print(reversed_arr)

[5 4 6 3 2 1]


In [2]:
#(b)Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods
arr1 = np.array([[1, 2], [2, 4], [5, 1], [2, 3]])
flattened_arr = arr1.flatten()
# or arr1.ravel()
print(flattened_arr)

[1 2 2 4 5 1 2 3]


In [3]:
#(c) Compare the following numpy arrays:
# arr1 = np.array([[1, 2], [3, 4]])
# arr2 = np.array([[1, 2], [3, 4]])

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
are_equal = np.array_equal(arr1, arr2)
print(are_equal)

True


In [5]:
#(d) Find the most frequent value and their indice(s) in the following arrays:
# i. x = np.array([1,2,3,4,5,1,2,1,1,1])
# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1])
counts = np.bincount(x)
most_frequent_value = np.argmax(counts)
indices = np.where(x == most_frequent_value)
print(f"Most frequent value in x: {most_frequent_value}")
print(f"Indices of the most frequent value: {indices}")

y = np.array([1, 1, 2, 3, 4, 2, 2, 3, 1])
counts = np.bincount(y)
most_frequent_value = np.argmax(counts)
indices = np.where(y == most_frequent_value)
print(f"Most frequent value in y: {most_frequent_value}")
print(f"Indices of the most frequent value: {indices}")

Most frequent value in x: 1
Indices of the most frequent value: (array([0, 5, 7, 8]),)
Most frequent value in y: 1
Indices of the most frequent value: (array([0, 1, 8]),)


In [9]:
# (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
# i. Sum of all elements
# ii. Sum of all elements row-wise
# iii. Sum of all elements column-wise

arr = np.array([[4, 3, 1], [2, 3, 4], [5, 6, 1]])

# Sum of all elements
total_sum = np.sum(arr)
print(f"Sum of all elements: {total_sum}")

# Sum of all elements row-wise (axis=1)
row_sums = np.sum(arr, axis=1)
print(f"Sum of all elements row-wise: {row_sums}")

# Sum of all elements column-wise (axis=0)
col_sums = np.sum(arr, axis=0)
print(f"Sum of all elements column-wise: {col_sums}")



Sum of all elements: 29
Sum of all elements row-wise: [ 8  9 12]
Sum of all elements column-wise: [11 12  6]
Eigen values: [ 9.33526157  1.3275421  -2.66280367]
Eigen vectors: 
[[-0.45085838 -0.76029633  0.15579186]
 [-0.57394906  0.63973083 -0.60601857]
 [-0.68360017  0.11266744  0.78004512]]
Inverse of the matrix: 
[[ 0.63636364 -0.09090909 -0.27272727]
 [-0.54545455  0.03030303  0.42424242]
 [ 0.09090909  0.27272727 -0.18181818]]


In [19]:
# (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
# i. Sum of diagonal elements
# ii. Eigen values of matrix
# iii. Eigen vectors of matrix
# iv. Inverse of matrix
# v. Determinant of matrix

import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
diagonal_sum = np.trace(n_array)
print(f"Sum of diagonal elements: {diagonal_sum}")

import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
eigenvalues, eigenvectors = np.linalg.eig(n_array)

print(f"Eigen values: {eigenvalues}")
print(f"Eigen vectors: \n{eigenvectors}")

import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
inverse_matrix = np.linalg.inv(n_array)

print(f"Inverse of the matrix: \n{inverse_matrix}")

import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
determinant = np.linalg.det(n_array)

print(f"Determinant of the matrix: {determinant}")

Sum of diagonal elements: 176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors: 
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix: 
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


In [10]:
#(g) Multiply the following matrices and also find covariance between matrices using NumPy:
# i. p = [[1, 2], [2, 3]]
# q = [[4, 5], [6, 7]]
# ii. p = [[1, 2], [2, 3], [4, 5]]
# q = [[4, 5, 1], [6, 7, 2]]

p = np.array([[1, 2, 3], [1, 2, 3]])
q = np.array([[1, 6], [7, 1]])

# Matrix multiplication
try:
    product = np.matmul(p, q)
    print(f"Product of p and q: \n{product}")
except ValueError as e:
    print(f"Cannot multiply p and q: {e}")
    # The inner dimensions of the matrices must match.
    # p is 2x3, q is 2x2. This multiplication is not possible.

# Let's use the matrices from the question for the next part
p = np.array([[1, 2, 3], [1, 2, 3]])
q = np.array([[1, 2, 1], [4, 5, 2]])
# This multiplication is also not possible (2x3 and 2x3).

# Let's assume we're asked to multiply p by the transpose of q
q_transposed = q.T  # Transpose of q is a 3x2 matrix
product = np.matmul(p, q_transposed)
print(f"Product of p and transpose of q: \n{product}")

# Covariance
p_for_cov = np.array([[1, 2, 3], [4, 5, 6], [7, 2, 1]])
covariance_matrix = np.cov(p_for_cov)
print(f"Covariance matrix of p_for_cov: \n{covariance_matrix}")

Cannot multiply p and q: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
Product of p and transpose of q: 
[[ 8 20]
 [ 8 20]]
Covariance matrix of p_for_cov: 
[[ 1.          1.         -3.        ]
 [ 1.          1.         -3.        ]
 [-3.         -3.         10.33333333]]


In [11]:
# (h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
# find inner, outer and cartesian product?

x = np.array([2, 4])
y = np.array([1, 5, 10, 3])

inner_product = np.inner(x, y[:2])  # Inner product needs same length arrays, so using first two elements of y
print(f"Inner product of x and first two elements of y: {inner_product}")

outer_product = np.outer(x, y)
print(f"Outer product of x and y: \n{outer_product}")

# Cartesian product (not a direct NumPy function, but can be done using `np.meshgrid`)
cartesian_product = np.array(np.meshgrid(x, y)).T.reshape(-1, 2)
print(f"Cartesian product of x and y: \n{cartesian_product}")


Inner product of x and first two elements of y: 22
Outer product of x and y: 
[[ 2 10 20  6]
 [ 4 20 40 12]]
Cartesian product of x and y: 
[[ 2  1]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 4  1]
 [ 4  5]
 [ 4 10]
 [ 4  3]]


In [12]:
# Q2: Based on NumPy Mathematics and Statistics
# (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
# i. Find element-wise absolute value
# ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
# row.
# iii. Mean, Median and Standard Deviation of flattened array, of each column, and
# each row

import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)
print("Absolute Value:\n", abs_array)

# ii. Percentiles (flattened, column-wise, row-wise)
# Flattened array
flattened = array.flatten()
p25_flat = np.percentile(flattened, 25)
p50_flat = np.percentile(flattened, 50)
p75_flat = np.percentile(flattened, 75)

print("\nPercentiles (Flattened):")
print("25th:", p25_flat)
print("50th (Median):", p50_flat)
print("75th:", p75_flat)

# Column-wise percentiles
print("\nPercentiles (Column-wise):")
for i in range(array.shape[1]):
    col = array[:, i]
    print(f"Column {i}: 25th = {np.percentile(col, 25)}, 50th = {np.percentile(col, 50)}, 75th = {np.percentile(col, 75)}")

# Row-wise percentiles
print("\nPercentiles (Row-wise):")
for i in range(array.shape[0]):
    row = array[i]
    print(f"Row {i}: 25th = {np.percentile(row, 25)}, 50th = {np.percentile(row, 50)}, 75th = {np.percentile(row, 75)}")

# iii. Mean, Median, Std Dev
# Flattened
print("\nStatistics (Flattened):")
print("Mean:", np.mean(flattened))
print("Median:", np.median(flattened))
print("Standard Deviation:", np.std(flattened))

# Column-wise
print("\nStatistics (Column-wise):")
print("Mean:", np.mean(array, axis=0))
print("Median:", np.median(array, axis=0))
print("Standard Deviation:", np.std(array, axis=0))

# Row-wise
print("\nStatistics (Row-wise):")
print("Mean:", np.mean(array, axis=1))
print("Median:", np.median(array, axis=1))
print("Standard Deviation:", np.std(array, axis=1))

Absolute Value:
 [[1 2 3]
 [4 5 6]]

Percentiles (Flattened):
25th: -3.5
50th (Median): -0.5
75th: 2.5

Percentiles (Column-wise):
Column 0: 25th = -2.75, 50th = -1.5, 75th = -0.25
Column 1: 25th = -0.25, 50th = 1.5, 75th = 3.25
Column 2: 25th = -3.75, 50th = -1.5, 75th = 0.75

Percentiles (Row-wise):
Row 0: 25th = -0.5, 50th = 1.0, 75th = 2.0
Row 1: 25th = -5.0, 50th = -4.0, 75th = 0.5

Statistics (Flattened):
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Statistics (Column-wise):
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Statistics (Row-wise):
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


In [16]:
# (b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
# and truncated value, rounded values
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
rounded_vals = np.round(a)

print("\nFloor Values:", floor_vals)
print("Ceiling Values:", ceil_vals)
print("Truncated Values:", trunc_vals)
print("Rounded Values:", rounded_vals)


Floor Values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling Values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated Values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values: [-2. -2. -0.  0.  2.  2.  3.]


In [14]:
# Q3: Based on Searching and Sorting
# (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
# i. Sorted array
# ii. Indices of sorted array
# iii. 4 smallest elements
# iv. 5 largest elements

import numpy as np

# Define the array
array = np.array([5.5, 2, 9, 1.1, 3, 8, 7.7, 4, 6, 0.5])

# i. Sorted array
sorted_array = np.sort(array)
print("Sorted Array:", sorted_array)

# ii. Indices of sorted array
sorted_indices = np.argsort(array)
print("Indices of Sorted Array:", sorted_indices)

# iii. 4 smallest elements
smallest_4 = np.sort(array)[:4]
print("4 Smallest Elements:", smallest_4)

# iv. 5 largest elements
largest_5 = np.sort(array)[-5:][::-1]
print("5 Largest Elements:", largest_5)

Sorted Array: [0.5 1.1 2.  3.  4.  5.5 6.  7.7 8.  9. ]
Indices of Sorted Array: [9 3 1 4 7 0 8 6 5 2]
4 Smallest Elements: [0.5 1.1 2.  3. ]
5 Largest Elements: [9.  8.  7.7 6.  5.5]


In [17]:
# (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
# i. Integer elements only
# ii. Float elements only

# i. Integer elements only
int_elements = array[array == array.astype(int)]
print("Integer Elements:", int_elements)

# ii. Float elements only
float_elements = array[array != array.astype(int)]
print("Float Elements:", float_elements)

Integer Elements: [2. 9. 3. 8. 4. 6.]
Float Elements: [5.5 1.1 7.7 0.5]


In [18]:
# Q4:
# (a) Write a function named img_to_array(path) that reads an image from a specified path and
# save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
# images)
import cv2
import numpy as np
import os

def img_to_array(path):
    # Read image in color and grayscale mode
    img_color = cv2.imread(path, cv2.IMREAD_COLOR)
    img_gray = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

    if img_color is None:
        print("Error: Image not found or invalid path.")
        return

    # Determine if it's grayscale
    if np.array_equal(cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY), img_gray):
        # It's grayscale
        array = img_gray
        filename = os.path.splitext(os.path.basename(path))[0] + "_grayscale.txt"
        print("Image is Grayscale.")
    else:
        # It's color (RGB - OpenCV reads as BGR)
        array = cv2.cvtColor(img_color, cv2.COLOR_BGR2RGB)
        filename = os.path.splitext(os.path.basename(path))[0] + "_rgb.txt"
        print("Image is RGB.")

    # Save array to a text file
    np.savetxt(filename, array.reshape(-1, array.shape[-1]) if array.ndim == 3 else array, fmt='%d')
    print(f"Array saved to {filename}")